name: new-plugin
on:
  push:
    branches:
      - "main"
    paths:
      - "plugins/**"

# Prevent running this workflow concurrently
concurrency:
  group: "matrix-messages"

jobs:
  setup:
    name: Collect metadata and setup job matrix
    runs-on: ubuntu-latest
    timeout-minutes: 40
    if: github.repository == 'nix-community/nixvim'

    outputs:
      plugins: ${{ steps.get_info.outputs.json }}
      pr_number: ${{ steps.pr.outputs.number }}
      pr_url: ${{ steps.get_pr.outputs.url }}
      pr_author_name: ${{ steps.get_pr.outputs.author_name }}
      pr_author_url: ${{ steps.get_pr.outputs.author_url }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v26
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Get plugins info
        id: get_info
        run: |
          # Run the `plugin-info` tool, printing the result to write to GITHUB_OUTPUT
          echo "json=$(
            nix run .#plugin-info -- \
              -c \
              'github:${{ github.repository }}/${{ github.event.before }}'
          )" >> $GITHUB_OUTPUT

      - name: Get PR info
        id: get_pr
        if: steps.get_info.outputs.json != '{}'
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          # `gh` will have already printed to stderr, so no need to parse the response json
          JSON=$(
            gh api  \
              -H "Accept: application/vnd.github+json" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              /repos/${{ github.repository }}/commits/${{ github.sha }}/pulls
          ) || exit 1

          if [[ "$(echo "$JSON" | jq -c '.')" = "[]" ]]; then
            # No associated PR
            # TODO: does this need special handling?
          else
            # Print key=value pairs to GITHUB_OUTPUT
            echo "$JSON" | \
              jq -r '.[0] | { number: .number, url: .html_url, author_name: .user.login, author_url: .user.html_url } | to_entries[] | "\(.key)=\(.value)"' \
              >> $GITHUB_OUTPUT
          fi

  send:
    name: Send matrix message
    runs-on: ubuntu-latest
    needs: setup
    if: ${{ fromJSON(needs.setup.outputs.plugins).removed == [] && fromJSON(needs.setup.outputs.plugins).added != [] }}
    strategy:
      matrix:
        added: ${{ fromJSON(needs.setup.outputs.plugins).added }}
    env:
      name: ${{ matrix.added.name }}
      plain: ${{ matrix.added.plain }}
      html: ${{ matrix.added.html }}
      markdown: ${{ matrix.added.markdown }}
      pr_number: ${{ needs.setup.outputs.pr_number }}
      pr_url: ${{ needs.setupt_pr.outputs.pr_url }}
      pr_author_name: ${{ needs.setupt_pr.outputs.pr_author_name }}
      pr_author_url: ${{ needs.setupt_pr.outputs.pr_author_url }}

    steps:
      - name: Install matrix-msg tool
        uses: lkiesow/matrix-notification@v1
        with:
          token: ${{ secrets.CI_MATRIX_TOKEN }}
          server: ${{ secrets.CI_MATRIX_SERVER }}
          room: ${{ secrets.CI_MATRIX_ROOM }}
          tool: true

      - name: Send message and print summary
        run: |
          # Message text; plain-text & html
          # TODO: format as-per existing announcements
          # See available env-vars above
          msg="Hello, world!"

          # stdout
          echo "$plain"

          # markdown summary
          echo "$markdown" >> $GITHUG_STEP_SUMMARY

          # matrix message
          matrix-msg "$plain" "$html"
          # TODO: update stdout/step_summary with msg success/failure

  report:
    name: Report removed plugins
    runs-on: ubuntu-latest
    needs: setup
    if: ${{ fromJSON(needs.setup.outputs.plugins).removed != [] }}
    env:
      json: ${{ needs.setup.outputs.plugins }}
      pr_number: ${{ needs.setup.outputs.pr_number }}
      pr_url: ${{ needs.setupt_pr.outputs.pr_url }}
      pr_author_name: ${{ needs.setupt_pr.outputs.pr_author_name }}
      pr_author_url: ${{ needs.setupt_pr.outputs.pr_author_url }}

    steps:
      - name: Comment on PR
        if: ${{ needs.setup.outputs.pr_number }}
        env:
          GH_TOKEN: ${{ github.token }}
          BODY: |
            Hi from new-plugin workflow!
        run: |
          gh pr comment '${{ needs.setup.outputs.pr_number }}' \
            --repo '${{ github.repository }}' \
            --body "$BODY"
